apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      valuesObject:
        provider:
          name: aws
        env:
          - name: AWS_DEFAULT_REGION
            value: ap-northeast-2
        serviceAccount:
          name: external-dns
        domainFilters:
          - chaosplane.dev
        policy: sync
        sources:
          - ingress
        txtOwnerId: chaosplane-prod
        nodeSelector:
          nodepool: system
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
