// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"

	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/config"
	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/database"
	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/handler"
)

func InitializeServer(ctx context.Context) (*Server, error) {
	cfg := config.New()
	pool, err := database.NewPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler(pool)
	srv := New(cfg, pool, healthHandler)
	return srv, nil
}
