// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"

	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/config"
	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/database"
	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/handler"
	"github.com/chaosplane-hq/chaosplane-platform/apps/api/internal/service"
)

func InitializeServer(ctx context.Context) (*Server, error) {
	cfg := config.New()
	pool, err := database.NewPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler(pool)
	rdb := NewRedisClient(cfg)
	authService := service.NewAuthService(pool, cfg, rdb)
	authHandler := handler.NewAuthHandler(authService)
	hierarchyService := service.NewHierarchyService(pool)
	hierarchyHandler := handler.NewHierarchyHandler(hierarchyService)

	k8sClient, err := service.NewK8sClient(cfg)
	if err != nil {
		return nil, err
	}

	experimentService := service.NewExperimentService(k8sClient)
	policyService := service.NewPolicyService(k8sClient)

	experimentHandler := handler.NewExperimentHandler(experimentService)
	policyHandler := handler.NewPolicyHandler(policyService)
	wsHandler := handler.NewWebSocketHandler(experimentService)

	srv := New(cfg, pool, healthHandler, authHandler, hierarchyHandler, experimentHandler, policyHandler, wsHandler, rdb, authService)
	return srv, nil
}
