apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: chaosplane-api
    newName: 988261628566.dkr.ecr.ap-northeast-2.amazonaws.com/chaosplane/api
    newTag: db59417
  - name: chaosplane-web
    newName: 988261628566.dkr.ecr.ap-northeast-2.amazonaws.com/chaosplane/web
    newTag: db59417
